// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzcugiuwaoxxtcttxuex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6Y3VnaXV3YW94eHRjdHR4dWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjA1MjIsImV4cCI6MjA3MTYzNjUyMn0.JEhAWHUGXqezwSIAsIn4b101eCOUKPaMtWx1A0d-xY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});